docs/home_assistant.md, docs/troubleshooting.md, lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/GUI/GUI.cpp, lib/GUI/GUI.h, platformio.ini, src/Settings.h, src/main.cpp, src/main.h
Also added configurable reporting of telemetry, devices, and rooms
=> Make maxDistance configurable, move around mqtt topics

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/util.h
Add initial support for meater
Improve msft:cdp fingerprint
=> Add support for ATC_MiThermometer

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/GUI.cpp, lib/BleFingerprint/GUI.h, platformio.ini
This fixes the delay that occurred when launching room assistant app.
=> Requery if room assistant broadcast found after query

src/main.cpp, src/main.h
Prevent the error message described in https://github.com/ESPresense/ESPresense/issues/258#issuecomment-1038852168
=> Disable I2C sensors if I2C is disabled

src/main.cpp
=> Remove BME280 & TSL2561 configuration log messages

src/main.cpp, src/main.h
If you check the box your node will update with whatever is latest including prereleases.
=> Add prerelease checkbox

src/main.cpp, src/main.h
- Add a option to set a +/- offset to the read temperature before sending to mqtt
- Standardize with a single decimal point accuracy for temperature/humidity
Related issue/enhancement discussion: https://github.com/ESPresense/ESPresense/issues/370
=> DHT Sensor temp related changes

src/MotionSensors.cpp, src/MotionSensors.h, src/main.cpp, src/main.h
=> Pulled motion sensors logic out into it's own code files

src/BME280Sensor.cpp, src/BME280Sensor.h, src/TSL2561Sensor.cpp, src/TSL2561Sensor.h, src/defaults.h, src/main.cpp, src/main.h
Following the same pattern as before, small changes to reuse common pub code.
=> Two more sensor platform cleanups

src/HX711.cpp, src/HX711.h, src/main.cpp, src/main.h
=> Support for hx711 load sensors

src/main.cpp
Adding highwatermark for stack overflow debugging to telemetry
=> Add stack high watermark for scanTask and reportTask to telemetry

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/util.h
=> Add tractive

.github/workflows/build.yml, .gitignore, lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/string_utils.cpp, lib/BleFingerprint/string_utils.h, platformio.ini, src/BME280Sensor.cpp, src/HX711.cpp, src/MotionSensors.cpp, src/TSL2561Sensor.cpp, src/main.cpp, src/main.h
=> Initial esp32c3 support, also upgrade esp32 framework to 3.5.

platformio.ini, src/HttpReleaseUpdate.cpp, src/HttpReleaseUpdate.h, src/main.h
=> Improve auto update performance

platformio.ini, src/main.cpp
Make WiFi connection timeout configurable (Fixes #503)
=> Make WiFi connection timeout configurable (Fixes #503)

src/Battery.cpp, src/Battery.h, src/DHT.cpp, src/MotionSensors.cpp, src/main.cpp
=> Make PIR type configurable

src/BH1750.cpp
Hi, first of all big thanks to this project! iPhone 12 tracking has been rock solid. 
However BH1750 lux sensor didn't work at all after first measurement. After that nothing. This will fix readings and also prevent flooding mqtt api with sensor delay like other sensors have. 
BME280 works ok.
ESP32 with v3.0.4
Cheers,
-m
=> Fix BH1750

lib/network/Network.h, src/main.cpp
previous pull request (#734) was incomplete and should have included this change as well...
=> previous pull incomplete

lib/BleFingerprint/util.h, src/Enrollment.cpp, src/mqtt.cpp, src/mqtt.h
This also includes the fix to slugify enrollment name to an id
=> Have nodes broadcast an ibeacon advertisement

platformio.ini, src/AHTX0.cpp, src/AHTX0.h, src/main.cpp, src/main.h
I have added support for AHT10/AHT20 temperature and humidity sensors, which can be found e.g. on Aliexpress in combination with a BMP20 as a cheap replacement for the - at least currently - quite expensive BME20, and would be happy to contribute my code.
=> Added support for AHT10/AHT20 temperature + humidity sensors

src/defaults.h, src/globals.h, src/main.cpp, src/mqtt.cpp
More details in the issue: https://github.com/ESPresense/ESPresense/issues/782
=> Add a configuration option for the Home Assistant Discovery Prefix

platformio.ini, src/DS18B20.cpp, src/DS18B20.h, src/main.cpp, src/main.h
Add support for DS18B20 sensors.
This supports multiple sensors chained onto the same pin.
Adds the OneWire library and DallasTemperature to support this.
=> Add support for DS18B20 sensors

src/Button.cpp, src/Button.h, src/GUI.cpp, src/GUI.h, src/Switch.cpp, src/Switch.h, src/main.cpp, src/main.h
Added Switches and Buttons. 2 of each so we have options. Followed the pattern set forth in the Motion sensor (also why there are two)
Being able to install these ESP32s at useful places like light switches and door switches will increase functionality of ESPresense as we won't need an additional ESPHome device sited next to our ESPresense device to handle this use case.
I will update the https://espresense.com/sensors github source if/when this pull is accepted.
=> Switches buttons

src/main.cpp
=> Turn off deprecated send to rooms (you can still enable it again until v4)

platformio.ini
This should fix https://github.com/ESPresense/ESPresense/issues/1013
=> Use updated version of esphome/ESPAsyncWebServer

lib/BleFingerprint/BleFingerprintCollection.cpp
This led to sometimes at startup fingerprints would get the incorrect config (id, name or rssi@1m)
=> Fix race condition

lib/network/Network.h, src/main.cpp
Adding support for EST-PoE-32 to the ethernet configuration.
Hopefully I did it correctly, let me know if there is any other changes I need to make
=> Add support for EST-PoE-32

src/SensirionSGP30.cpp
- Corrected measure interval: must be once per second, following chips specs. (See also comments on #1163). 
- Created a separate reporting interval to assure reporting to MQTT is still only done once a minute. 
- Corrected TVOC device class to match unit of measurements reported to ppb. (This addresses issue [1164](https://github.com/ESPresense/ESPresense/issues/1164)).
=> SGP30: Corrected measure interval, added separate Reporting Interval, Corrected TVOC device class
