ESPresense/ESPresense

platformio.ini, src/main.cpp, src/main.h
I have around 20 Temperature & Humidity sensors around the house, which all could be obsolete, if this new BT & Motion detector would measure Temperature & Humidity. 
This also has the advantage of getting the data much faster, as from battery driven devices for example to turn on the fan in the bathroom much quicker if someone is in the shower.  
I added support for the 2 most used sensors, the DHT11 and the DHT22 with Home Assistant Auto Discover.
https://github.com/smrtnt/Open-Home-Automation/tree/master/ha_mqtt_sensor_dht22 
What I could not found out, how Home Assistant handles the temperature values if the System Settings are in Fahrenheit and a sensor reports in Celsius. Are they converted internal, or should I let the user choose between reporting Celsius or Fahrenheit?
Maybe it …
=> Add support for Temperature and Humidity sensor 

.gitignore, lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/BleFingerprintCollection.cpp, lib/BleFingerprint/BleFingerprintCollection.h, lib/BleFingerprint/strings.cpp, lib/BleFingerprint/strings.h, lib/BleFingerprint/util.h, platformio.ini, src/main.cpp, src/main.h
We can now connect to btle devices and ask for characteristics.  This means we can append the model number to all apple fingerprints.  
This also adds support for the room assistant app on iPhones which gets you a unique uuid for any phone it's installed on. 
Fixes #69 and #39!
=> Add device model to apple fingerprints add support room assistant app

src/main.cpp
Apparently it's "config" not "configuration"
=> Fix entity category

.gitignore, platformio.ini, src/defaults.h, src/main.cpp, src/main.h
Adds support for the I2C version of the BME280 and TSL2561 sensors as well as support for two I2C buses.
More info: 
- BME280: https://www.bosch-sensortec.com/products/environmental-sensors/humidity-sensors-bme280/
- TSL2561: https://ams.com/en/tsl2561
=> I2C BME280 & TSL2561 support + two I2C buses

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/util.h
Adding Vanmoof bicycle fingerprinting. Tested with an S3 and X3. Using MAC address since it seems like it doesn't change.
=> feat: add vanmoof fingerprinting

src/main.h
Adding UOM for humidity to be consistent with other published sensors. Also allows senor to draw correct graph in HA.
=> Include Humidity for discovered sensor

BUILDING.md, DEBUGGING_FREERTOS.md
Added details to build instructions to changing PlatformIO project environment.
Added documentation to allow stack debugging of FreeRTOS using Eclipse as an IDE as there is no plugin for this available for PlatformIO.
=> FreeRTOS stack debugging documentation

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/rssi.h, lib/BleFingerprint/util.h
This patch adds support for tags which all report themselves as having
the same identifier: `name:nut`, but do all have distinct unchanging MAC
addresses.  The patch changes the reported ID to be `nut:<mac address>`.
Fixes #466.
=> Add support for `nut` type tags

src/BME280Sensor.cpp, src/HX711.cpp
After running this for a while, I noticed that both ESPresense instances I had with BME280 sensors were constantly showing 8C above what my ESPHome sensor was showing.
I later learned that Bosch recommended to set oversampling to 1x, enable "Forced mode" and disable the filter (for weather monitoring) to prevent overheating.
(My ESPHome instances also use those settings)
This change will also result in a much lower power consumption
=> Prevent BME280 from overheating

lib/BleFingerprint/GUI.cpp, lib/BleFingerprint/GUI.h, src/MotionSensors.cpp, src/MotionSensors.h, src/defaults.h, src/main.cpp, src/main.h
Added support for radar debounce period, which delays reporting the 'NO MOTION' state with a configurable number of milliseconds. As discussed https://github.com/ESPresense/ESPresense/discussions/462
This setting advertises itself via MQTT, so next to the ESPresense web interface, the debounce period can be configured through MQTT messages, as well as from the device entities in Home Assistant. 
Getting the proper range and steps in Home Assistant, required me to extend the properties of `void sendNumberDiscovery` (`src/main.h`) so it correctly advertises itself via MQTT discovery.
=> Radar no-motion state debounce period

.github/workflows/build.yml, lib/BleFingerprint/GUI.cpp, platformio.ini
We copy firmware files to old locations so auto-updating should work just fine, but downgrading will be annoying because it'll revert to non-sensor versions.  Not sure it can be helped.  Making this part of v3.
=> Remove huzzah flavor, make all variants sensor enabled, m5atom-matrix renamed m5atom

lib/BleFingerprint/BleFingerprintCollection.cpp, lib/BleFingerprint/BleFingerprintCollection.h, src/defaults.h, src/main.cpp
- Reboot if no bluetooth advertisements seen in the last 2.5 minutes.  Ensure we don't reboot until after checking for an update.
- Reduce portal timeout to 5 minutes
=> Watchdog for ble controller

src/BH1750.cpp
Decreased sensor interval from 60 sec to 2 sec, for rapid sensor readings.
This helps a lot in a plethora of light-related automations based on this value. This was also mentioned in #744.
=> Update BH1750 sensor interval

lib/BleFingerprint/BleFingerprint.cpp
When we receive a config message from MQTT before we've seen the associated tracker we don't correctly update the rssi@1m value when we get a Bluetooth frame from the tracker later on.
This patch ensures that we correctly update the rssi@1m value.
Steps to reproduce:
1. Publish a config update for a tracker, e.g. for topic `espresense/settings/irk:00000000000000000000000000000000/config`:
```json
{"id":"apple_watch","name":"Apple Watch","rssi@1m":-42}
```
2. Note how the reports for `espresense/devices/apple_watch/NODE` contain the **correct** rssi@1m value.
3. Reboot the node.
4. Observe that the reports now use the **incorrect** fallback value.
=> Ensure that setting rssi@1m works after a reboot

src/main.cpp, src/mqtt.cpp
Attempts to fix #997. I _think_ I got them all, however HA still is showing me the below three. For the life of me I cannot find where those would be set or if it's just bad historical data or something.
* status_led
* active_scan
* ota_update
=> fix: rename mqtt entities to conform to new home assistant reqs

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/string_utils.cpp
**Add missing return in BleFingerprint::fingerprintServiceAdvertisements**
This isn't _strictly_ required because `setId()` ignores "downgrades" to more generic ID types (i.e. from `ID_TYPE_FLORA` to `ID_TYPE_AD` in this case) but skips running unnecessary code and makes the code more readable.
**Fix incorrect check in hextostr()**
This function decodes hex-encoded strings (e.g. "41" -> "A"). Previously we'd check whether the output buffer's size is a multiple of two. This would incorrectly reject valid uses of the function. Instead we should check the input string's length.
=> Add missing return in BleFingerprint::fingerprintServiceAdvertisements / Fix incorrect check in hextostr()

lib/BleFingerprint/BleFingerprint.cpp, lib/BleFingerprint/BleFingerprint.h, lib/BleFingerprint/BleFingerprintCollection.cpp
When a device's MAC address changes we attempt to keep old distance measurements. This can be improved by also copying the filter state and a few more related values.
Here's an example where the old mechanism leads to a random spike for the distance measurement:
=> Copy all statistics values when a device's MAC address changes

.gitignore, platformio.ini, src/build_timestamp.cpp, src/build_timestamp.h, src/main.cpp, src/main.h, update_ts.py
I've found this rather useful when repeatedly deploying updated firmware images to a large number of nodes.
The patch carefully avoids full rebuilds of any "real" source files by putting the timestamp into a separate .cpp file. It also works around PlatformIO's build cache that would happily permanently cache the timestamp file if we were using `__DATE__`.
The Python script isn't entirely necessary because we could just simply `touch` the timestamp file via `extra_scripts` to force a rebuild. But we'd need _some_ kind of script anyway and this way we can format the timestamp more easily than is possible with C++.
=> Add build timestamp to the version number

ui/src/stores.js
I use a reverse proxy for tls & proxying traffic to my espresense nodes. The config & ui pages work fine, but the websocket connection fails on the devices page here:
```
new WebSocket(`${location.origin.replace("http://", "ws://")}/ws`))
```
Since my `window.location.origin` starts with `https://`, the replace doesn't happen. I need `wss://` instead of `ws://`. 
This is the error I see in the browser console:
```
index.js:1  Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'https' is not allowed.
at https://espr1.myhouse.com/ui/index.js:1:22244
at Object.subscribe (https://espr1.myhouse.com/ui/index.js:1:6827)
at o (https://espr1.myhouse.com/ui/index.js:1:393)
at i (https://espr1.myhouse.com/ui/index.js:1:491)
at zt …
```
=> Add https:// -> wss:// replace call

src/DS18B20.cpp
I have 1 device that occasionally has the DS18B20 sensor give a bad value of -127. A second device with 8 sensors is giving me this bad sensor value every few minutes. Likely do to poor build quality on my part. 
This fix checks for that low, invalid value of -127 and skips the data publish.
=> Sensor DS18B20  Check to Skip Null Values

src/SensirionSGP30.cpp
Every second is a bit overkill causing home assistant to struggle to visualise the data. Every 5 seconds should be better.
=> Increase internal time

include/defaults.h
This is a more reasonable value (still conservative) for a default path loss exponent.  And since we're doing a breaking change, this is the time to change it.
=> Set default absorption to 3 (was 3.5)
